from sample_batch.catalog import (
    CRITERION_FACTORING,
    CRITERION_GRAPH,
    CRITERION_WORD_PROBLEM,
)
from sample_batch.profiles import StudentProfile, solid_profile

SOLID_PROFILES: tuple[StudentProfile, ...] = (
    solid_profile(
        "ana-torres",
        "Ana Torres",
        "blue",
        30,
        "Check: (x + 2)(x + 3) = x^2 + 3x + 2x + 6 = x^2 + 5x + 6",
        "The maximum is 24 C and it happens at 11:00.",
        "The bus averages 63 km/h, which is reasonable for a school route.",
        ground_truth={
            CRITERION_FACTORING: 4.0,
            CRITERION_GRAPH: 3.0,
            CRITERION_WORD_PROBLEM: 3.0,
        },
        notes="Complete work with verification on every item.",
    ),
    solid_profile(
        "valentina-suarez",
        "Valentina Suarez",
        "dark_blue",
        29,
        "Check by expanding: (x + 2)(x + 3) = x^2 + 5x + 6, same trinomial.",
        "The curve peaks at 24 C at 11:00 and cools afterwards.",
        "So the bus keeps an average of 63 km/h over the whole trip.",
        ground_truth={
            CRITERION_FACTORING: 4.0,
            CRITERION_GRAPH: 3.0,
            CRITERION_WORD_PROBLEM: 3.0,
        },
        notes="Flawless work: expansion check, maximum with time, interpretation.",
    ),
    solid_profile(
        "andres-molina",
        "Andres Molina",
        "black",
        32,
        "Product 6, sum 5: correct.",
        "Max 24 C at 11:00.",
        "63 km/h",
        ground_truth={
            CRITERION_FACTORING: 3.5,
            CRITERION_GRAPH: 3.0,
            CRITERION_WORD_PROBLEM: 2.5,
        },
        notes="Correct throughout; terse justification and no closing interpretation.",
    ),
    solid_profile(
        "lucia-navarro",
        "Lucia Navarro",
        "blue",
        28,
        "Check: expanding gives x^2 + 5x + 6 again, so the factors hold.",
        "The maximum temperature is 24 C.",
        "The average speed of the bus is 63 km/h.",
        ground_truth={
            CRITERION_FACTORING: 4.0,
            CRITERION_GRAPH: 2.5,
            CRITERION_WORD_PROBLEM: 3.0,
        },
        notes="Missed the time of the maximum; everything else complete.",
    ),
    solid_profile(
        "gabriela-mendez",
        "Gabriela Mendez",
        "graphite",
        31,
        "2 times 3 is 6 and 2 plus 3 is 5.",
        "It tops out at 24 C at 11:00 before dropping.",
        "That means the bus averaged 63 km/h, a normal city-route speed.",
        ground_truth={
            CRITERION_FACTORING: 3.5,
            CRITERION_GRAPH: 3.0,
            CRITERION_WORD_PROBLEM: 3.0,
        },
        notes="Factor check verified numerically but not by expansion.",
    ),
    solid_profile(
        "mateo-quintero",
        "Mateo Quintero",
        "dark_blue",
        33,
        "Verified: (x + 2)(x + 3) expands to the original trinomial.",
        "Highest value: 24 C, reached at 11:00.",
        "Final answer: 63 km/h average speed.",
    ),
    solid_profile(
        "isabela-cardenas",
        "Isabela Cardenas",
        "blue",
        27,
        "Check: x * x = x^2, 2 + 3 = 5, 2 * 3 = 6. It matches.",
        "The graph reaches its maximum of 24 C at 11:00.",
        "84 divided by 4/3 gives 63, so 63 km/h.",
    ),
    solid_profile(
        "santiago-herrera",
        "Santiago Herrera",
        "black",
        30,
        "I expanded the factors and got x^2 + 5x + 6 back.",
        "Peak temperature: 24 C at 11:00.",
        "The bus travels at 63 km/h on average.",
    ),
    solid_profile(
        "daniela-osorio",
        "Daniela Osorio",
        "graphite",
        29,
        "Check: sum of roots -5, product 6, factors (x + 2)(x + 3).",
        "Between those hours it warms 4 C; the max is 24 C at 11:00.",
        "v = d / t = 84 / (4/3) = 63 km/h",
    ),
    solid_profile(
        "sebastian-rincon",
        "Sebastian Rincon",
        "blue",
        32,
        "Both factors check out: product 6, sum 5.",
        "Max: 24 C at 11:00, then the room cools down.",
        "So the average speed comes to 63 km/h exactly.",
    ),
    solid_profile(
        "camilo-fuentes",
        "Camilo Fuentes",
        "dark_blue",
        31,
        "Quick check: 2 * 3 = 6, 2 + 3 = 5, so (x + 2)(x + 3) is right.",
        "The maximum on the graph is 24 C and it occurs at 11:00.",
        "Converting 80 minutes to 4/3 h gives v = 63 km/h.",
    ),
    solid_profile(
        "renata-aguilar",
        "Renata Aguilar",
        "black",
        28,
        "Expansion check: x^2 + 3x + 2x + 6 = x^2 + 5x + 6.",
        "It climbs to a maximum of 24 C at 11:00.",
        "The unit conversion gives 4/3 h, so the speed is 63 km/h.",
    ),
    solid_profile(
        "nicolas-serrano",
        "Nicolas Serrano",
        "graphite",
        30,
        "The pair (2, 3) multiplies to 6 and adds to 5, so it works.",
        "Reading the graph: maximum 24 C at 11:00.",
        "Speed = 84 km over 4/3 h = 63 km/h for the whole ride.",
    ),
)
