from autocurricula.core.fleet.declarations import (
    FIRESTORE_CHECKPOINT,
    GCS_FETCH_BATCH,
    INFRASTRUCTURE_PRINCIPALS,
    LLM_GENERATE,
    SIS_WRITE_GRADES,
    TOOL_CAPABILITIES,
    AgentDeclaration,
    PrincipalDeclaration,
    capability_for_tool,
)
from autocurricula.core.fleet.enforcement import (
    annotate_span,
    authorize,
    authorize_firestore_write,
    authorize_gcs_read,
    authorize_llm,
    build_default_authorizer,
    get_authorizer,
    principal_of,
    reset_authorizer_cache,
    set_authorizer,
)
from autocurricula.core.fleet.identity import (
    agent_principals,
    all_principals,
    build_grants,
    runtime_service_account,
)
from autocurricula.core.fleet.registry import build_fleet_registry
from autocurricula.core.fleet.roster import (
    AGENT_DECLARATIONS,
    AGENTS_BY_ID,
    ARMOR_SCREENER_ID,
    CALIBRATION_EVALUATOR_ID,
    CURRICULUM_AUDITOR_ID,
    FALLBACK_EVALUATOR_ID,
    GRADING_AGENT_ID,
    META_OPTIMIZER_AUDIT_ID,
    META_OPTIMIZER_GRADING_ID,
    PROMPT_PROPOSER_ID,
    RISK_DETECTOR_ID,
    SCHEMA_REPAIR_ID,
    SECOND_OPINION_ID,
)

EXAM_FETCHER_PRINCIPAL = "exam-fetcher"
ORCHESTRATOR_PRINCIPAL = "pipeline-orchestrator"
SIS_WRITER_PRINCIPAL = "sis-writer"

__all__ = [
    "AGENTS_BY_ID",
    "AGENT_DECLARATIONS",
    "ARMOR_SCREENER_ID",
    "CALIBRATION_EVALUATOR_ID",
    "CURRICULUM_AUDITOR_ID",
    "EXAM_FETCHER_PRINCIPAL",
    "FALLBACK_EVALUATOR_ID",
    "FIRESTORE_CHECKPOINT",
    "GCS_FETCH_BATCH",
    "GRADING_AGENT_ID",
    "INFRASTRUCTURE_PRINCIPALS",
    "LLM_GENERATE",
    "META_OPTIMIZER_AUDIT_ID",
    "META_OPTIMIZER_GRADING_ID",
    "ORCHESTRATOR_PRINCIPAL",
    "PROMPT_PROPOSER_ID",
    "RISK_DETECTOR_ID",
    "SCHEMA_REPAIR_ID",
    "SECOND_OPINION_ID",
    "SIS_WRITER_PRINCIPAL",
    "SIS_WRITE_GRADES",
    "TOOL_CAPABILITIES",
    "AgentDeclaration",
    "PrincipalDeclaration",
    "agent_principals",
    "all_principals",
    "annotate_span",
    "authorize",
    "authorize_firestore_write",
    "authorize_gcs_read",
    "authorize_llm",
    "build_default_authorizer",
    "build_fleet_registry",
    "build_grants",
    "capability_for_tool",
    "get_authorizer",
    "principal_of",
    "reset_authorizer_cache",
    "set_authorizer",
    "runtime_service_account",
]
